### PR TITLE
CS-136 - Dependency updates to bring in latest profile change (commas on location)

### PR DESCRIPTION
**Pull request by mdyoung3**
# READY FOR REVIEW

# Summary
- Brings in latest change from Cardinal Service Profile
- Dependency update
- Ticket: https://stanfordits.atlassian.net/browse/CS-136

# Review By (Date)
- When does this need to be reviewed by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by pookmish** [comment]
Can you run `composer update su-sws/*` one more time. I just created a release for stanford_profile_helper

**Comment by pookmish** [comment]
Also, require the dev version of node_revision delete to avoid issues. `composer require drupal/node_revision_delete:2.0.x-dev`

**Comment by mdyoung3** [comment]
@pookmish Done

**Review by pookmish — APPROVED** [review]
GTG

**Pull request merged**
